apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomcat.fullname" . }}
  labels:
    {{- include "tomcat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
    - port: {{ .Values.app.debug.remote.port }}
      targetPort: debug
      protocol: TCP
      name: debug
      {{- if eq "NodePort" .Values.app.service.type }}
      nodePort: {{ .Values.app.debug.remote.nodePort }}
      {{- end }}
  selector:
    {{- include "tomcat.selectorLabels" . | nindent 4 }}
