apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tomcat.fullname" . }}
  labels:
    {{- include "tomcat.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "tomcat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/type: "tomcat"
        {{- include "tomcat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tomcat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.app.debug.remote.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "tomcat.fullname" . }}-config-volume
              readOnly: true
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
            - name: {{ include "tomcat.fullname" . }}-config-volume
              readOnly: true
              mountPath: /usr/local/tomcat/conf/context.xml
              subPath: context.xml
            {{- if .Values.app.license.enabled }}
            - name: {{ include "tomcat.fullname" . }}-config-volume
              readOnly: true
              mountPath: /usr/local/tomcat/.license
              subPath: .license
            {{- end }}
          {{- if .Values.app.debug.remote.enabled }}
          env:
            - name: CATALINA_OPTS
              value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port={{ .Values.app.debug.remote.port }} -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: {{ include "tomcat.fullname" . }}-config-volume
          configMap:
            name: {{ include "tomcat.fullname" . }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
