{{- if .Values.ingress.enabled -}}
{{- $fullName := include "current-chart.fullname" . -}}
{{- $servicePort := .Values.app.ports.service -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    {{- else }}
    kubernetes.io/ingress.class: "nginx-{{ .Release.Namespace }}"
    {{- end }}
    
    {{- if .Values.ingress.bodySize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.bodySize | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    {{- include "current-chart.labels" . | nindent 4 }}
spec:
  rules:
  - {{ if .Values.ingress.host -}}
    host: {{ .Values.ingress.host | quote }}
    {{ end -}}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $servicePort }}
        path: {{ .Values.ingress.path }}($|/)(.*)
        pathType: Prefix
{{- end }}